### ISSUE TITLE
Push an OCI image archive (`.tar`) to a Docker registry

### ISSUE THREAD

**Issue by shrink** [pr-mpt/actions-push-oci-archive-to-registry#1]
```yaml
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          labels: "${{ steps.meta.outputs.labels }}"
          outputs: "type=oci,dest=image.tar"
          tags: "${{ steps.meta.outputs.tags }}"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
```

```yaml
skopeo copy --all \
    oci-archive:docker-image-oci.tar \
    docker://ghcr.io/pr-mpt/test-docker-buildx-output-types:multi
```
